version: '3.8'

services:
  dev:
    image: mcr.microsoft.com/devcontainers/javascript-node:20-bullseye
    user: node
    platform: linux/arm64
    environment:
      PGHOST: ${PGHOST}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      SSH_AUTH_SOCK: /run/host-services/ssh-auth.sock
    volumes:
      - node_home_data:/home/node
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock:ro
    ports:
      - 5173:5173
    depends_on:
      postgres:
        condition: service_healthy
    command: /bin/sh -c "while sleep 1000; do :; done"

  postgres:
    image: postgres:15-alpine
    platform: linux/arm64
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  node_home_data: